sample_app/config/routes.rb
Rails.application.routes.draw do
  
  resources :sessions, :only => [:new, :create, :destroy]

  get 'sessions/new'

  root "pages#home"

  get '/contact' => "pages#contact"

  get '/about' => "pages#about"

  get '/help' => "pages#help"
  
  get '/signup' => "users#new"
  get '/signin' => "sessions#new"
  get '/signout' => "sessions#destroy"

  resources :users

end

sample_app/app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id         :integer          not null, primary key
#  nom        :string
#  email      :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
require 'digest'

class User < ActiveRecord::Base

  attr_accessor :password
  attr_accessible :nom, :email, :password, :password_confirmation
 

  email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :nom,  :presence => true,
                    :length   => { :maximum => 50 }
  validates :email, :presence => true,
                    :format   => { :with => email_regex },
                    :uniqueness => { :case_sensitive => false }
  validates :password, :presence     => true,
                       :confirmation => true,
                       :length       => { :within => 6..40 } 
   before_save :encrypt_password

  def has_password?(password_soumis)
    encrypted_password == encrypt(password_soumis)
  end

  def self.authenticate(email, submitted_password)
    user = find_by_email(email)
    return nil  if user.nil?
    return user if user.has_password?(submitted_password)
  end

  def self.authenticate_with_salt(id, cookie_salt)
    user = find_by_id(id)
    (user && user.salt == cookie_salt) ? user : nil
  end

  private

    def encrypt_password
      self.salt = make_salt if new_record?
      self.encrypted_password = encrypt(password)
    end

    def encrypt(string)
      secure_hash("#{salt}--#{string}")
    end

    def make_salt
      secure_hash("#{Time.now.utc}--#{password}")
    end

    def secure_hash(string)
      Digest::SHA2.hexdigest(string)
    end
end

sample_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

sample_app/app/controllers/pages_controller.rb
class PagesController < ApplicationController
  
  def home
  	@titre = "Accueil"
  end

  def contact
  	@titre = "Contact"
  end

  def about
  	@titre = "About"
  end

  def help
  	@titre = "Help"
  end
  
   def help
    @title = "Aide"
  end

end

sample_app/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @titre = "S'identifier"
  end

  def create
    user = User.authenticate(params[:session][:email],
                             params[:session][:password])
    if user.nil?
      flash.now[:error] = "Combinaison mail/mot de passe invalide."
      @titre = "Sign in"
      render 'new'
    else
      sign_in user
      redirect_back_or user
    end
  end

 def destroy
    sign_out
    redirect_to root_path
  end
end

sample_app/app/controllers/users_controller.rb
# == Schema Information
#
# Table name: users
#
#  id         :integer          not null, primary key
#  nom        :string
#  email      :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class UsersController < ApplicationController
   
    before_filter :authenticate, :only => [:edit, :update]
    before_filter :correct_user, :only => [:edit, :update]

     def index
    @titre = "Tous les utilisateurs"
    @users = User.paginate(:page => params[:page])
  end


    def show
    	@user = User.find(params[:id])
   		@titre = @user.nom
  	end

  def new
  	 @user = User.new
     @title = "S'inscrire"
  end

 def create
    @user = User.new(params[:user])
    if @user.save
      flash[:success] = "Bienvenue dans l'Application Exemple!"
      redirect_to @user
    else
      @titre = "Inscription"
      render 'new'
    end
  end

  def edit
    @titre = "Édition profil"
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(params[:user])
      flash[:success] = "Profil actualisé."
      redirect_to @user
    else
      @titre = "Édition profil"
      render 'edit'
    end
  end

   private

   def authenticate
      deny_access unless signed_in?
    end

    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_path) unless current_user?(@user)
    end


end

sample_app/app/helpers/application_helper.rb
module ApplicationHelper

	 # Retourner un titre basé sur la page.
  def titre
    base_titre = "Simple App du Tutoriel Ruby on Rails"
    if @titre.nil?
      base_titre
    else
      "#{base_titre} | #{@titre}"
    end
  end

  def logo
    image_tag("42-logo.png", :alt => "Application Exemple", :class => "round")
  end

end

sample_app/app/helpers/sessions_helper.rb
module SessionsHelper


	def sign_in(user)
    cookies.permanent.signed[:remember_token] = [user.id, user.salt]
      #self.current_user = user
  end

    def current_user?(user)
     user == current_user
  end


  def signed_in?
    !@current_user.nil?
  end

  def sign_out
    cookies.delete(:remember_token)
    self.current_user = nil
  end

  def deny_access
    store_location
    redirect_to signin_path, :notice => "Please sign in to access this page."
  end

  def redirect_back_or(default)
    redirect_to(session[:return_to] || default)
    clear_return_to
  end

  private

    def user_from_remember_token
      User.authenticate_with_salt(*remember_token)
    end

    def remember_token
      cookies.signed[:remember_token] || [nil, nil]
    end

    def deny_access
    redirect_to signin_path, :notice => "Merci de vous identifier pour rejoindre cette page."
  	end

  	def store_location
      session[:return_to] = request.fullpath
    end

    def clear_return_to
      session[:return_to] = nil
    end

end

sample_app/app/helpers/users_helper.rb
# == Schema Information
#
# Table name: users
#
#  id         :integer          not null, primary key
#  nom        :string
#  email      :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

module UsersHelper
	 def gravatar_for(user, options = { :size => 50 })
    	gravatar_image_tag(user.email.downcase,  :alt => user.nom,
                                           		 :class => 'gravatar',
                                          		 :gravatar => options)
  end
end

sample_app/app/views/layouts/_footer.html.erb
<footer>
  <nav class="round">
    <ul>
      <li><%= link_to "À Propos", about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><a href="http://news.railstutorial.org/">News</a></li>
      <li><a href="http://www.railstutorial.org/">Rails Tutorial</a></li>
    </ul>
  </nav>
</footer>

sample_app/app/views/layouts/_header.html.erb
<header>
  <%= link_to logo, root_path %>
  <nav class="round">
    <ul>
      <li><%= link_to "Accueil", root_path %></li>
      <% if signed_in? %>
      <li><%= link_to "Utilisateurs", users_path %></li>
      <li><%= link_to "Profil", current_user %></li>
      <li><%= link_to "Réglages", edit_user_path(current_user) %></li>
      <% end %>
      <li><%= link_to "Aide", help_path %></li>
      <% if signed_in? %>
      <li><%= link_to "Déconnexion", signout_path, :method => :delete %></li>
      <% else %>
      <li><%= link_to "S'identifier", signin_path %></li>
      <% end %>
    </ul>
  </nav>
</header>

sample_app/app/views/layouts/_stylesheets.html.erb
<!--[if lt IE 9]>
<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->
<%= stylesheet_link_tag 'blueprint/screen', :media => 'screen' %>
<%= stylesheet_link_tag 'blueprint/print',  :media => 'print' %>
<!--[if lt IE 8]><%= stylesheet_link_tag 'blueprint/ie' %><![endif]-->
<%= stylesheet_link_tag 'custom', :media => 'screen' %>

sample_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= @title %></title>
    <%= csrf_meta_tag %>
    <%= render 'layouts/stylesheets' %>
  </head>
  <body>
    <div class="container">
      <%= render 'layouts/header' %>
      <section class="round">
        <%= yield %>
      </section>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

sample_app/app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(object.errors.count, "error") %> 
        prohibited this <%= object.class.to_s.underscore.humanize.downcase %> 
        from being saved:</h2>
    <p>There were problems with the following fields:</p>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

sample_app/app/views/users/edit.html.erb
<h1>Edition du profil</h1>

<%= form_for(@user) do |f| %>
  <%= render 'shared/error_messages', :object => f.object %>
  <div class="field">
    <%= f.label :nom, "Nom" %><br />
    <%= f.text_field :nom %>
  </div>
  <div class="field">
    <%= f.label :email, "eMail" %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation,"Confirmation" %><br />
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit "Update" %>
  </div>
<% end %>

<div>
  <%= gravatar_for @user %>
  <a href="http://gravatar.com/emails">changer</a>
</div>

sample_app/app/views/users/index.html.erb
<h1>Liste des utilisateurs</h1>

<%= will_paginate %>

<ul class="users">
  <% @users.each do |user| %>
    <li>
      <%= gravatar_for user, :size => 30 %>
      <%= link_to user.nom, user %>
    </li>
  <% end %>
</ul>

<%= will_paginate %>

sample_app/app/views/users/new.html.erb
<h1>Inscription</h1>

<%= form_for(@user) do |f| %>
	 <%= render 'shared/error_messages', :object => f.object %>
  <div class="field">
    <%= f.label :nom %><br />
    <%= f.text_field :nom %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation, "Confirmation" %><br />
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit "Inscription" %>
  </div>
<% end %>

sample_app/app/views/users/show.html.erb
<table class="profile" summary="Information profil">
  <tr>
    <td class="main">
      <h1>
        <%= gravatar_for @user %>
        <%= @user.nom %>
      </h1>
    </td>
    <td class="sidebar round">
      <strong>Nom</strong> <%= @user.nom %><br />
      <strong>URL</strong>  <%= link_to user_path(@user), @user %>
    </td>
  </tr>
</table>